version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
test-module:
    image: 
    container_name: indranasaha/testindrepo:firsttry
    depends_on:
      - chrome
environment:
      - MODULE=testng.xml
      - BROWSER=chrome
      - hubHost=selenium-hub
